#!/bin/bash
#$ -S /bin/bash
#$ -q short.q
#$ -N quantify
#$ -V
#$ -cwd
#$ -b n
#$ -pe smp 8
#$ -l mem_requested=8G,tmp_requested=150G,tmpfree=150G

# Cell Ranger directory
CELLRANGER_PATH=/share/ScratchGeneral/annsen/pipelines/cellranger-3.1.0
INPUT_CSV=${SGE_O_WORKDIR}/arrayed_aggr.csv
OUTPUT_DIR=/share/ScratchGeneral/annsen/data/experimental_data/CLEAN/CROP-seq

# LOAD CELL RANGER INTO BACKGROUND
export PATH=$CELLRANGER_PATH:$PATH
source $CELLRANGER_PATH/sourceme.bash

# GO TO OUTPUT DIRECTORY
cd $OUTPUT_DIR

# Run CELL RANGER 3.1
cellranger aggr --id=ARRAYED_AGGR --csv=$INPUT_CSV --normalize=mapped

