#!/bin/bash
#$ -S /bin/bash
#$ -q short.q
#$ -N quantify
#$ -V
#$ -cwd
#$ -b n
#$ -pe smp 16
#$ -l mem_requested=8G,tmp_requested=150G,tmpfree=150G

# Cell Ranger directory
CELLRANGER_PATH=/share/ScratchGeneral/annsen/pipelines/cellranger-3.1.0
INPUT_DIR=/directflow/GWCCGPipeline/projects/bioinformatics/R_190327_ALEHEW_EXT_10X/20190327_ALEHEW_EXT_10X/190702_A00152_0121_AHLK3WDSXX/analysis/demux/outs/fastq_path
REF_DIR=/share/ScratchGeneral/annsen/data/reference_data/Homo_sapiens.CROPseq.2019/Homo_sapiens.CROPseq.2019
OUTPUT_DIR=/share/ScratchGeneral/annsen/data/experimental_data/CLEAN/CROP-seq

# LOAD CELL RANGER INTO BACKGROUND
export PATH=$CELLRANGER_PATH:$PATH
source $CELLRANGER_PATH/sourceme.bash

# GO TO OUTPUT DIRECTORY
cd $OUTPUT_DIR

# Run CELL RANGER 3.1
cellranger count --id=AH_pool-1 \
                   --transcriptome=${REF_DIR} \
                   --fastqs=${INPUT_DIR} \
                   --sample=AH_pool-1 \
                   --force-cells=20000 \
                   --nosecondary \
                   --localcores=16 \
                   --localmem=128

