#!/bin/bash
#$ -S /bin/bash
#$ -q short.q
#$ -N star
#$ -V
#$ -cwd
#$ -b n
#$ -pe smp 16
#$ -l mem_requested=8G,tmp_requested=150G,tmpfree=150G

STAR_PATH=/share/ScratchGeneral/annsen/pipelines/cellranger-3.1.0/STAR/5dda596

INPUT_DIR=/share/ScratchGeneral/annsen/data/experimental_data/RAW/CROP-seq/processed
OUTPUT_DIR=/share/ScratchGeneral/annsen/data/experimental_data/CLEAN/CROP-seq/MiSeq
REF_DIR=/share/ScratchGeneral/annsen/data/reference_data/Homo_sapiens.CROPseq.2019/Homo_sapiens.CROPseq.2019/star

export PATH=$STAR_PATH:$PATH
cd $OUTPUT_DIR

for INPUT_FILE in ${INPUT_DIR}/*.fastq; do
    SAMPLE_ID=${INPUT_FILE%.*}

    STAR --genomeDir $REF_DIR --readFilesCommand cat \
    --readFilesIn $INPUT_FILE \
    --outSAMtype BAM SortedByCoordinate \
    --quantMode GeneCounts \
    --runThreadN 16 \
    --outFileNamePrefix ${SAMPLE_ID}_ \
    --outReadsUnmapped Fastx \
    --outFilterScoreMinOverLread 0 \
    --outFilterMatchNminOverLread 0 \
    --outFilterMatchNmin 0 \
    --outFilterMismatchNmax 2
done